# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
ARG NODE_VERSION=current-alpine
FROM node:$NODE_VERSION AS base
LABEL maintainer="ubbn"

ARG PNPM_VERSION=latest
ENV PNPM_VERSION=$PNPM_VERSION

RUN apk update && apk add --no-cache libc6-compat
RUN corepack enable
RUN corepack prepare pnpm@$PNPM_VERSION --activate

# Create app directory
WORKDIR /app

# Copy dependency definitions
COPY ./package.json ./

# Install dependencies
RUN pnpm install

# Copy the source code
COPY . .

# Build the project
RUN pnpm run build

# Ensure the entry point is executable
RUN chmod +x build/index.js

# Start the MCP server (CMD overridden by runtime config if provided)
CMD ["node", "build/index.js"]