# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
ARG NODE_VERSION=22-alpine
FROM node:${NODE_VERSION}
# Create app directory
WORKDIR /app

# Copy dependency definitions
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the source code
COPY . .

# Build the project
RUN npm run build

# Ensure the entry point is executable
RUN chmod +x build/index.js

# Start the MCP server (CMD overridden by runtime config if provided)
CMD ["node", "build/index.js"]